import {StyleSheet, Dimensions} from 'react-native';

const {height, width} = Dimensions.get('screen');

const FoodScreenStyles = StyleSheet.create({
  linearGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    position: 'relative',
  },
  topContainer: {
    flex: 1,
    maxHeight: 75,
    width: width,
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  topText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 22,
    padding: 10,
    marginTop: 13,
    letterSpacing: 3,
  },
  middleContainer: {
    flex: 4,
  },
  bottomContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    maxHeight: 130,
    height: '100%',
    padding: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  bottomRight: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  box: {
    flexDirection: 'row',
    backgroundColor: 'rgb(82, 0, 0)',
    borderColor: 'rgb(102, 0, 0)',
    height: 100,
    width: width,
    padding: 15,
    borderBottomWidth: 1,
  },
  left: {
    flex: 2,
  },
  img: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  middle: {
    flex: 4,
    paddingLeft: 10,
  },
  title: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16,
  },
  categoryWrapper: {
    flexDirection: 'row',
  },
  category: {
    color: 'white',
    padding: 4,
    fontSize: 10,
  },
  right: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkbox: {
    width: 32,
    height: 32,
  },
  addBtn: {
    backgroundColor: 'rgba(246, 190, 0, 0.8)',
    height: 55,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 35,
    marginHorizontal: 20,
    marginTop: 5,
    borderWidth: 2,
    borderColor: 'rgba(0, 0, 0, 1)',
    width: width / 3,
  },
  addText: {
    color: 'white',
    fontWeight: '700',
    letterSpacing: 3,
  },
  allCheckbox: {
    width: 32,
    height: 32,
    marginTop: 9,
  },
  selectedText: {
    color: 'white',
  },
  formContainer: {
    zIndex: 4,
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: width / 1.25,
    borderWidth: 1,
    borderColor: '#F0C400',
    borderRadius: 30,
    position: 'absolute',
    top: '20%',
    left: '50%',
    marginLeft: -width / 2.5,
    backgroundColor: 'black',
    padding: 10,
    shadowColor: '#F0C400',
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 10,
  },
  formTitle: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    maxHeight: 70,
    fontSize: 20,
    letterSpacing: 1,
    padding: 5,
    height: '100%',
    color: 'white',
    marginBottom: 15,
  },
  formTop: {
    flex: 2,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  inputLabel: {
    color: 'white',
  },
  label: {
    color: 'white',
    fontSize: 10,
    marginLeft: 8,
  },
  textInput: {
    height: 50,
    width: width / 1.5,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0)',
    marginVertical: 5,
    borderRadius: 25,
    color: 'black',
    backgroundColor: 'rgba(255,255, 255, 1)',
    textAlign: 'center',
  },
  formMiddle: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  checkboxContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
  },
  formBottom: {
    flex: 1,
  },
  checkboxBox: {
    width: width / 1.25 / 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
  },
  smallCheckbox: {
    height: 25,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  formAddBtn: {
    backgroundColor: 'rgba(246, 190, 0, 0.8)',
    height: 55,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 35,
    marginRight: 10,
    marginTop: 5,
    borderWidth: 2,
    borderColor: 'rgba(0, 0, 0, 1)',
    width: width / 2.4,
    marginVertical: 15,
  },
  formBackBtn: {
    backgroundColor: 'rgba(246, 190, 0, 0.6)',
    height: 55,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 35,
    marginTop: 5,
    borderWidth: 2,
    borderColor: 'rgba(0, 0, 0, 1)',
    width: width / 4,
    marginVertical: 15,
  },
  buttonWrapper: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  formError: {
    color: 'red',
    fontSize: 12,
    fontWeight: '600',
    paddingVertical: 10,
    paddingHorizontal: 5,
    textAlign: 'center',
  },
  blur: {
    zIndex: 3,
    position: 'absolute',
    left: 0,
    top: 0,
    height: '100%',
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  formStatus: {
    color: 'white',
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
    padding: 30,
  },
});

export default FoodScreenStyles;
