const requireImg = name => {
  switch (name) {
    case 'ausmenakebabs.jpg':
      return require('../assets/restaurants/ausmenakebabs.jpg');
    case 'befrites.jpg':
      return require('../assets/restaurants/befrites.jpg');
    case 'berzipanna.jpg':
      return require('../assets/restaurants/berzipanna.jpg');
    case 'cafeleningrad.jpg':
      return require('../assets/restaurants/cafeleningrad.jpg');
    case 'cillipica.jpg':
      return require('../assets/restaurants/cillipica.jpg');
    case 'circlek.jpg':
      return require('../assets/restaurants/circlek.jpg');
    case 'donerking.jpg':
      return require('../assets/restaurants/donerking.jpg');
    case 'ezitismigla.jpg':
      return require('../assets/restaurants/ezitismigla.jpg');
    case 'fatpopo.jpg':
      return require('../assets/restaurants/fatpopo.jpg');
    case 'foodbox.jpg':
      return require('../assets/restaurants/foodbox.jpg');
    case 'ghettopietura.jpg':
      return require('../assets/restaurants/ghettopietura.jpg');
    case 'hasana.jpg':
      return require('../assets/restaurants/hasana.jpg');
    case 'hesburger.jpg':
      return require('../assets/restaurants/hesburger.jpg');
    case 'jugla.jpg':
      return require('../assets/restaurants/jugla.jpg');
    case 'kebabhouse.jpg':
      return require('../assets/restaurants/kebabhouse.jpg');
    case 'kfc.jpg':
      return require('../assets/restaurants/kfc.jpg');
    case 'kingu.jpg':
      return require('../assets/restaurants/kingu.jpg');
    case 'latenightmunchies.jpg':
      return require('../assets/restaurants/latenightmunchies.jpg');
    case 'lauvasnams.jpg':
      return require('../assets/restaurants/lauvasnams.jpg');
    case 'lazycats.jpg':
      return require('../assets/restaurants/lazycats.jpg');
    case 'lido.jpg':
      return require('../assets/restaurants/lido.jpg');
    case 'lokalskarbonades.jpg':
      return require('../assets/restaurants/lokalskarbonades.jpg');
    case 'martinapica.jpg':
      return require('../assets/restaurants/martinapica.jpg');
    case 'mazaterapija.jpg':
      return require('../assets/restaurants/mazaterapija.jpg');
    case 'mcdonald.jpg':
      return require('../assets/restaurants/mcdonald.jpg');
    case 'mrbobs.jpg':
      return require('../assets/restaurants/mrbobs.jpg');
    case 'narvesen.jpg':
      return require('../assets/restaurants/narvesen.jpg');
    case 'oakburgers.jpg':
      return require('../assets/restaurants/oakburgers.jpg');
    case 'pepperonipizza.jpg':
      return require('../assets/restaurants/pepperonipizza.jpg');
    case 'picalulu.jpg':
      return require('../assets/restaurants/picalulu.jpg');
    case 'picudarbnica.jpg':
      return require('../assets/restaurants/picudarbnica.jpg');
    case 'pizzaitalia.jpg':
      return require('../assets/restaurants/pizzaitalia.jpg');
    case 'rigaskebabs.jpg':
      return require('../assets/restaurants/rigaskebabs.jpg');
    case 'streetburgers.jpg':
      return require('../assets/restaurants/streetburgers.jpg');
    case 'streetfood.jpg':
      return require('../assets/restaurants/streetfood.jpg');
    case 'vairaksaules.jpg':
      return require('../assets/restaurants/vairaksaules.jpg');
    default:
      return require('../assets/restaurants/default.jpg');
  }
};

export default requireImg;
