import {StyleSheet, Dimensions} from 'react-native';

const {height, width} = Dimensions.get('screen');

const FoodScreenStyles = StyleSheet.create({
  linearGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: '100%',
    width: '100%',
  },
  top: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topContainer: {
    flex: 5,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  filterBtnContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 10,
  },
  filterBtn: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
    borderWidth: 1,
    borderColor: '#F0C400',
    margin: 5,
    borderRadius: 10,
    shadowColor: '#F0C400',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  filterBtnText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 12,
  },
  error: {
    flex: 3,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  errorText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 12,
  },
  spinner: {
    height: 100,
    width: 100,
    borderRadius: 100,
    borderWidth: 4,
    borderTopColor: '#F0C400',
    borderRightColor: '#444',
    borderBottomColor: '#F0C400',
    borderLeftColor: '#444',
    textAlign: 'center',
    position: 'absolute',
    top: '30%',
    marginLeft: -52,
    left: 0,
  },
  button: {
    position: 'absolute',
    top: '30%',
    left: 0,
    height: 96,
    width: 96,
    borderRadius: 100,
    marginTop: 2,
    marginLeft: -50,
    backgroundColor: 'red',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#F0C400',
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.75,
    shadowRadius: 30,
    elevation: 50,
  },
  buttonGradient: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
    borderRadius: 100,
  },
  text: {
    color: 'rgba(255,255,255, 0.8)',
    fontWeight: '700',
  },
  img: {
    borderRadius: 20,
    maxWidth: 300,
    height: 200,
    borderWidth: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderColor: 'rgba(246, 190, 0, 1)',
  },
  imgTextBox: {
    padding: 10,
    borderColor: 'red',
    borderRadius: 10,
    marginTop: 10,
  },
  imgText: {
    color: 'white',
    fontWeight: '700',
  },
  bottomContainer: {
    flex: 3,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
});

export default FoodScreenStyles;
